### ISSUE TITLE
이메일 중복 검사가 없어졌나요??????

### ISSUE THREAD

**Issue by woohyun212** [milideal/server#22]
분명 `User.Models`에 `isDuplicated`라는 함수가 있었고 그걸로 회원 가입 시에 이메일 중복 검사를 하는 걸로 알았었는데
어느 순간 보니까 없네요?

**Comment by yeonjunky** [comment]
https://github.com/milideal/server/commit/1481be4df98aba173ba0ce5527a57151a31fc138
해당 커밋에서 `email_exists`로 대체된 것 같습니다!
